exports = module.exports = function() {
  return function *(next) {
    if (this.path === '/favicon.ico') {
      var img = new Buffer('AAABAAEAEBAQAAEABAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAA/4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAQABAAEAAAAAEAEAEAAAAAABAQEAAAAAAAAREAAAAAEREREREREAAAAAERAAAAAAAAEBAQAAAAAAEAEAEAAAAAEAAQABAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAD//wAA/38AAP9/AAD3dwAA+28AAP1fAAD+PwAAwAEAAP4/AAD9XwAA+28AAPd3AAD/fwAA/38AAP//AAD//wAA', 'base64')
      this.type = 'image/jpeg'
      this.body = img
    } else yield next
  }
}